kim_tango/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from django.urls import reverse

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:register_profile')
urlpatterns = [
    path('',views.index,name='index'),
    path('rango/',include('rango.urls')),
#    path('static/',include(STATIC_URL)),
    path('admin/', admin.site.urls),
    path('accounts/register/',MyRegistrationView.as_view(),name='registration_register'),
    path('accounts/',include('registration.backends.simple.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/urls.py
from django.urls import path
#from django.conf.urls import url
#from django.urls import include
from rango import views 
app_name='rango'
urlpatterns=[
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/',views.add_category,name='add_category' ),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('restricted/', views.restricted, name='restricted'),
    path('search/',views.search, name="search"),
    path('account/<username>/',views.ProfileView.as_view(),name="profile"),
    path('register_profile/',views.register_profile,name="register_profile"),
    path('profiles/', views.ListProfilesView.as_view(), name='list_profiles'),
    path('goto/', views.goto_url, name='goto'),
    
]

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Category(models.Model):
    NAME_MAX_LENGTH = 128
    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):

        if self.views < 0:
            self.views = 0

        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    TITLE_MAX_LENGTH = 128
    URL_MAX_LENGTH = 200
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user =models.OneToOneField(User, on_delete=models.CASCADE)

    website=models.URLField(blank=True)
    picture=models.ImageField(upload_to='profile_images',blank=True)
    type=models.IntegerField(default=0);

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Page, Category
from django.contrib.auth.models import User
from rango.models import UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.NAME_MAX_LENGTH, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.TITLE_MAX_LENGTH, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=Page.URL_MAX_LENGTH, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)
    
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
        
        return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)
    class Meta:
        model = UserProfile
        exclude = ('user','type')

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse, response
from rango.models import Category, UserProfile
from rango.models import Page
from rango.forms import CategoryForm
from django.shortcuts import redirect
from django.urls import reverse
from rango.forms import PageForm
from rango.forms import UserForm,UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime
from rango.bing_search import run_query
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views import View
from django.utils.decorators import method_decorator

def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]

    context_dict = {}
    context_dict['boldmessage'] = 'Welcame to our site!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list

    response=render(request, 'rango/index.html', context=context_dict)
    #visitor_cookie_handler(request)

    #request.session.set_test_cookie()
    

    return response

def about(request):
    context_dict = {}
    #if request.session.test_cookie_worked():
    #    print("TEST COOKIE WORKED!")
    #    request.session.delete_test_cookie()
    return render(request, 'rango/about.html')



def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)

        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['pages'] = None
        context_dict['category'] = None
    
    return render(request, 'rango/category.html', context=context_dict)


@login_required
def register_profile(request):
    form = UserProfileForm()
    user_profile=UserProfile.objects.get_or_create(user=request.user)[0]
    user_profile.save()
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES,instance=user_profile)
    if form.is_valid():
        form.save()
        
        return redirect(reverse('rango:index'))
    else:
        print(form.errors)
    
    context_dict = {'form': form}
    return render(request, 'rango/profile_registration.html', context_dict)

'''
@login_required
def account_interface(request):
    cur_user=request.user
    userProfile=UserProfile.objects.filter(user=cur_user)[0]
    userForm=UserForm(instance=cur_user)
    userProfileForm=UserProfileForm(instance=userProfile)
    if request.method == 'POST' and userProfile:
        userProfileForm=UserProfileForm(request.POST, request.FILES,instance=userProfile)
    if userProfileForm.is_valid():
        userProfileForm.save()
        return redirect(reverse('rango:index'))
    
    

    context_dict = {"userForm":userForm,"userProfileForm":userProfileForm,'userProfile':userProfile}
    
    return render(request, 'rango/account_interface.html',context_dict)
'''
@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            cat=form.save(commit=True)
            #print(cat,cat.slug)
            return redirect('/rango/')
        else:
            print(form.errors)
    
    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except:
        category = None
    
    if category is None:
        return redirect(reverse('rango:index'))

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()

                return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
        else:
            print(form.errors) 
    
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)

def search(request):
    result_list = []
    query=None
    if request.method == 'POST':
        query = request.POST['keyword'].strip()
    if query is not None:
        # Run our Bing function to get the results list!
        result_list=Page.objects.filter(title__contains=query)
    return render(request, 'rango/search.html', {'result_list': result_list})


def goto_url(request):
    if request.method == 'GET':
        page_id = request.GET.get('page_id')
        try:
            selected_page = Page.objects.get(id=page_id)
        except Page.DoesNotExist:
            return redirect(reverse('rango:index'))
        selected_page.views = selected_page.views + 1
        selected_page.save()
        return redirect(selected_page.url)
    return redirect(reverse('rango:index'))



@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')



def visitor_cookie_handler(request):
    visits = int(request.COOKIES.get('visits', '1'))
    last_visit_cookie =request.COOKIES.get('last_visit',str(datetime.now()))
    
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],'%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    
    request.session['visits'] = visits

class ProfileView(View):
    def get_user_details(self, username):
        
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None
        user_profile = UserProfile.objects.get_or_create(user=user)[0]
       
        form = UserProfileForm({'website': user_profile.website, 'picture': user_profile.picture})
        return (user, user_profile, form)
    
    @method_decorator(login_required)
    def get(self, request, username):
        if(len(username)==0):
            username=request.user.username
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rango:index'))
        context_dict = {'user_profile': user_profile, 'selected_user': user, 'form': form}
        return render(request, 'rango/account_interface.html', context_dict)

    @method_decorator(login_required)
    def post(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rango:index'))
        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save(commit=True)
            return redirect('rango:profile', user.username)
        else:
            print(form.errors)
            context_dict = {'user_profile': user_profile,
            'selected_user': user,
            'form': form}
        return render(request, 'rango/account_interface.html', context_dict)

class ListProfilesView(View):
    @method_decorator(login_required)
    def get(self, request):
        profiles = UserProfile.objects.all()
        return render(request,'rango/list_profiles.html',{'user_profile_list': profiles})

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About Rango
{% endblock %}

{% block body_block %}

<h1>Rango says...</h1>
<div>
    here is the about page. <br />
    This website is used to provide online learning materials for programming enthusiasts.<br />
    Website Author: Four anger Dashshnd<br />
    
    <p>Visits: {{ visits }}</p>
</div>
<h2>Recommended programming language on this site</h2>
<img src="{% static 'images/Java.jpg' %}" alt="Picture of Java" />

<img src="{% static 'images/python.jpg' %}" alt="Picture of Python" />

<img src="{% static 'images/C programming.jpg' %}" alt="Picture of C" />

{% endblock %}

templates/rango/account_interface.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
Profile for {{ selected_user.username }}
{% endblock %}
{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">{{ selected_user.username }}'s Profile</h1>
    </div>
</div>

<div class="container">
    <div class="row">
        {% if user_profile.picture %}
            <img src="{{ MEDIA_URL }}{{ user_profile.picture }}" width="300" height="300" alt="{{ selected_user.username }}'s profile image" />
        {% else %}
            <img src="{{ MEDIA_URL }}cat.jpg" width="300" height="300" alt="{{ selected_user.username }}'s profile image" />
        {% endif %}
        <br />
        

        <div class="form-group" >
            {% if selected_user == user %}
            <p>
                <strong>Username:</strong>
               {{ user.username }}
            </p>
            <form role="form" method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <p class="required"><label class="required" for="id_email">
                        E-mail:</label>
                        <input class="form-control" id="id_email" name="email" type="email" value="{{ user.email }}" />
                    </p>

                    <p class="required"><label class="required" for="id_password1">
                        Website:</label>
                        <input class="form-control" id="id_password1" name="website" type="text" value="{{ user_profile.website }}"/>
                    </p>
                    
                    <p class="required">
                        <label for="id_picture">Picture:</label> <input type="file" name="picture" accept="image/*" id="id_picture">
                    </p>
                </div>
                <button type="submit" class="btn btn-primary">Update</button>
            </form>

            <form role="form" method="post" action="{% url 'auth_password_change'  %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <p class="required"><label for="id_old_password">Old password:</label> <input class="form-control"  type="password" name="old_password" autofocus="" required="" id="id_old_password"></p>
                    <p class="required"><label for="id_new_password1">New password:</label><input  class="form-control" type="password" name="new_password1" required="" id="id_new_password1"> <span class="helptext"></span></p><ul><li>Your password can't be too similar to your other personal information.</li><li>Your password must contain at least 6 characters.</li><li>Your password can't be a commonly used password.</li><li>Your password can't be entirely numeric.</li></ul><p></p>
                    <p class="required"><label for="id_new_password2">New password confirmation:</label> <input class="form-control"  type="password" name="new_password2" required="" id="id_new_password2"></p>
                </div>
                <button type="submit" class="btn btn-primary">Change Password</button>
            </form>

            {% else %}
                <p>
                    <strong>Website:</strong>
                    <a href="{{ user_profile.website }}">{{ user_profile.website }}</a>
                </p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}Add Page{% endblock %}
{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">Add a Page to {{category.name}}</h1>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <form role="form" id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
                {% csrf_token %}
                
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}<br/>
                    {{ field }}<br/>
                    <div class="p-2"></div>
                {% endfor %}
                <br />

                <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
                <div class="p-5"></div>
            </form>
        </div>
    </div>
{% endblock %}

templates/rango/base.html
<!doctype html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        
        
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Jekyll v3.8.5">

        <link rel="stylesheet" type="text/css" href="{% static 'css/header_styles.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/sidebar_styles.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/base_styles.css' %}">
        

        {% block style_block %}
        {% endblock %}


        <title>Rango- {% block title_block %}How to Tango with Django!{% endblock %}</title>
        <link rel="icon" href="{% static 'images/favicon.png' %}">
        

        

        <!-- Bootstrap core CSS--> 
        <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet">

        


        
        <!-- Custom styles for this template--> 
        <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
        <style> body {background-image: url('../../static/images/background.jpg');}</style> 
    </head>


    <body>
        
            <div class="body_header">
                {% block header_block %}
                    {% include 'rango/header.html' %}
                {% endblock %}
            </div>
            
            <div class="body_sidebar">
                {% block sidebar_block %}
                    {% get_category_list category %}
                   
                {% endblock %}
            </div>

            <div class="body_content">
                {% block body_block %}
                {% endblock %}
            </div>
            <footer >
                <p class="float-right"><a href="#">Back to top</a></p>
                <p class="copy_right">&copy; 2021 Four Anger Dashshnd &middot; <a href="#">Privacy</a> &middot;
                <a href="#">Terms</a></p>
            </footer>


            {% comment %}
        <!--<div class="container-fluid">
            <div class="row">
                <nav id="sidebarMenu" class="col-md-3 col-lg-auto d-md-block bg-light sidebar collapse">
                    <br/>
                    <div class="sidebar-sticky">
                        {% block sidebar_block %}
                            
                        {% endblock %}
                    </div>
                </nav>

                <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
                    {% block body_block %}
                    {% endblock %}
                    <footer>
                        <p class="float-right"><a href="#">Back to top</a></p>
                        <p>&copy; 2021 four anger dachshund &middot; <a href="#">Privacy</a> &middot;
                        <a href="#">Terms</a></p>
                    </footer>
                </main>
                
            </div>
            <div align="center"><img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" width="40%"></div>
            
        </div>-->
        {% endcomment %}
        

        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
        <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
    </body>


</html>



{% comment %}
<!--<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>
            Rango - 
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
        {% block body_block %}
        {% endblock %}
        </div>
        <div>
            {% block sidebar_block %}
            {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                    <li><a href="{% url 'auth_password_change' %}">Change Password</a></li>
                    <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                    <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
                {% else %}
                    <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
                    <li><a href="{% url 'auth_login' %}">Login</a></li>                     
                    <li class="nav-item"><a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a></li>
                     <li class="nav-item"><a class="nav-link" href="{% url 'rango:list_profiles' %}">List Profiles</a></li>
                {% endif %}
                    <li><a href="{% url 'rango:about' %}">About</a></li>
                    <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </div>
    </body>
</html> --> {% endcomment %}

templates/rango/bootstrap-base.html
<!doctype html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Rango- {% block title_block %}How to Tango with Django!{% endblock %}</title>
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard/">

    

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet">

    


    
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
  </head>
  <body>
    
    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
        <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Rango</a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>

            <li class="nav-item ">
              <a class="nav-link" href="{% url 'rango:about' %}">About</a></li>

            {% if user.is_authenticated %}
              <li class="nav-item ">
                <a class="nav-link"  href="{% url 'rango:restricted' %}">Restricted</a></li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>

              <li class="nav-item">
                <a class="nav-link"   href="{% url 'rango:add_category' %}">Add Category</a></li>

              <li class="nav-item">
                <a class="nav-link"   href="{% url 'auth_password_change' %}">Change Password</a></li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
                
              <li class="nav-item ">
                <a class="nav-link"   href="{% url 'auth_login' %}">Login</a></li>
            {% endif %}
         </ul>
        </div>
      </nav>
    </header>

    <div class="container-fluid">
      <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
          <div class="position-sticky pt-3">
            {% block sidebar_block %}
              {% get_category_list category %}
            {% endblock %}
          </div>
        </nav>

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          {% block body_block %}
          {% endblock %}
          <footer>
            <p class="float-right"><a href="#">Back to top</a></p>
            <p>&copy; 2020 Tango With Django 2 &middot; <a href="#">Privacy</a> &middot;
            <a href="#">Terms</a></p>
          </footer>
        </main>
      </div>
    </div>
    <!-- Bootstrap core JavaScript -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>

    <script src="https://getbootstrap.com/docs/4.2/assets/dist/js/bootstrap.bundle.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="dashboard.js"></script>
  </body>
</html>

templates/rango/categories.html
<ul class="nav flex-column">
    {% if categories %}
        {% for c in categories %}
            {% if c == current_category %}
                <li class="nav-item">
                    <strong><a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
                        <span data-feather="archive"></span>{{ c.name }}</a>
                    </strong>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rango:show_category' c.slug %}">
                        <span data-feather="archive"></span>{{ c.name }}
                    </a>
                </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li class="nav-item">There are no categories present.</li>
    {% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li>
                        <a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
                        {% if page.views > 1 %}
                            ({{ page.views }} views)
                        {% elif page.views == 1 %}
                            ({{ page.views }} view)
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}

        {% if user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br />
        {% endif %}
    {% else %}
        The specified category does not exist.
    {% endif %}
{% endblock %}

templates/rango/header.html
{% load staticfiles %}

    <header class='header-small fixed-top'>
        <a href='/'><img src="{% static 'images/favicon.png' %}" alt='site logo'/></a>
        {% include 'rango/header_nav.html' %}
        {% include 'rango/header_login.html' %}
        {% include 'rango/header_search.html' %}
    </header>

templates/rango/list_profiles.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
User Profiles
{% endblock %}
{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">User Profiles</h1>
        </div>
    </div>
    <div class="container">
        <div class="row">
            {% if user_profile_list %}
                <div class="panel-body">
                    <div class="list-group">
                        {% for list_user in user_profile_list %}
                            <div class="list-group-item">
                                <h4 class="list-group-item-heading">
                                    <a href="{% url 'rango:profile' list_user.user.username %}">
                                        {{ list_user.user.username }}
                                    </a>
                                </h4>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% else %}
                <p>There are no users present on Rango.</p>
            {% endif %}
        </div>

    </div>
{% endblock %}

templates/rango/recommend_article.html
<div class="index-widget wide tall">
    <h1 class="gm-header">Recently Recommended</h1>
    
      <a href="/" class="ginthusiasm-link">  <span class="gm-image">
        <img src="" alt="Image of ">
      </span>
    <span class="gm-title"> title</span></a>
      <div class="gm-desc">introduce</div>
    
</div>